server:
  port: ${PORT:8080}
spring.datasource:
  url: jdbc:h2:mem:productdb
  platform: h2
  driverClassName: org.h2.Driver
  username: sa
  password: 
  jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2.console:
    enabled: true
    path: h2-console