server:
  port: 8080
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers:
            - localhost:9092
      bindings:
          product-storage-out:
            destination: product-storage
            content-type: application/json