server:
  port: 8080
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers:
            - localhost:9092
          configuration:
            key.serializer: "org.apache.kafka.common.serialization.LongSerializer"
      bindings:
          product-event-storage-out:
            destination:  product-event-storage
            content-type: application/json
          productEventProcessor-in-0:
            destination: product-event-storage
            content-type: application/json
            group: evaluation
json:
  model:
    product:
      idPath: "$.id"
    